var y=Object.defineProperty;var g=(n,t,e)=>t in n?y(n,t,{enumerable:!0,configurable:!0,writable:!0,value:e}):n[t]=e;var d=(n,t,e)=>g(n,typeof t!="symbol"?t+"":t,e);class x{constructor(){d(this,"platform","gmail");d(this,"selectors",{composeToolbar:[".btC",".aDh"],composeBody:[".Am.aiL",'[role="textbox"][aria-label*="Body"]'],threadMessages:[".a3s.aiL","[data-message-id] .a3s"],senderName:[".gD"],subjectLine:[".hP"]})}extractThreadContext(){var l;if(typeof document>"u")return null;const t=document.querySelectorAll(this.selectors.threadMessages.join(", "));let e="";t.forEach((s,u)=>{var f,m,p,b;const a=(f=s.closest("[data-message-id]"))==null?void 0:f.querySelector(this.selectors.senderName.join(", ")),o=(a==null?void 0:a.getAttribute("name"))||((m=a==null?void 0:a.textContent)==null?void 0:m.trim())||`Sender ${u+1}`,i=((p=s.innerText)==null?void 0:p.trim())||((b=s.textContent)==null?void 0:b.trim())||"";i&&(e+=`--- ${o} ---
${i}

`)});const r=document.querySelector(this.selectors.subjectLine.join(", ")),c=((l=r==null?void 0:r.textContent)==null?void 0:l.trim())||"No Subject";return{threadText:e.trim()||"(No thread content found)",subject:c,sender:"Gmail User",platform:"gmail"}}insertDraft(t){if(typeof document>"u")return!1;const e=document.querySelector(this.selectors.composeBody.join(", "));return e?(e.focus(),e.isContentEditable?e.innerHTML=t.replace(/\n/g,"<br>"):(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement)&&(e.value=t),e.dispatchEvent(new Event("input",{bubbles:!0})),!0):!1}}class T{constructor(){d(this,"platform","outlook");d(this,"selectors",{composeToolbar:['[data-testid="ComposeSendButton"]',".ms-CommandBar"],composeBody:['[role="textbox"][aria-label*="Message body"]','[aria-label="Message body"]'],threadMessages:['[data-testid="MessageBody"]',".wide-content-host"],senderName:[],subjectLine:[]})}extractThreadContext(){if(typeof document>"u")return null;const t=document.querySelectorAll(this.selectors.threadMessages.join(", "));let e="";return t.forEach((r,c)=>{var s,u;const l=((s=r.innerText)==null?void 0:s.trim())||((u=r.textContent)==null?void 0:u.trim())||"";l&&(e+=`--- Message ${c+1} ---
${l}

`)}),{threadText:e.trim()||"(No thread content found)",subject:"",sender:"Outlook User",platform:"outlook"}}insertDraft(t){if(typeof document>"u")return!1;const e=document.querySelector(this.selectors.composeBody.join(", "));return e?(e.focus(),e.isContentEditable?e.innerHTML=t.replace(/\n/g,"<br>"):(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement)&&(e.value=t),e.dispatchEvent(new Event("input",{bubbles:!0})),!0):!1}}class h{static detectPlatform(t){const e=t.toLowerCase();return e.includes("mail.google.com")?"gmail":e.includes("outlook.live.com")||e.includes("outlook.office.com")||e.includes("outlook.office365.com")?"outlook":null}static getAdapter(t){return t==="gmail"?new x:new T}}(()=>{const n="ai-copilot-injected",t="ai-copilot-reply-btn";let e=0;const r=h.detectPlatform(window.location.hostname);if(!r)return;const c=h.getAdapter(r);function l(){e++;const o=document.createElement("button");return o.id=`${t}-${e}`,o.className=n,o.type="button",o.title="Reply with AI",o.setAttribute("aria-label","Reply with AI"),o.innerHTML=`
      <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" style="width:16px;height:16px;vertical-align:middle;margin-right:4px;">
        <path d="M10 1a6 6 0 0 1 6 6c0 2-1 3.8-2.5 4.9V14a1.5 1.5 0 0 1-1.5 1.5H8A1.5 1.5 0 0 1 6.5 14v-2.1C5 10.8 4 9 4 7a6 6 0 0 1 6-6z"/>
        <line x1="8" y1="18" x2="12" y2="18"/>
      </svg>
      <span>Reply with AI</span>
    `,o}function s(){const o=c.extractThreadContext();o&&chrome.runtime.sendMessage({type:"EMAIL_THREAD",threadText:o.threadText,subject:o.subject,sender:o.sender,platform:o.platform})}function u(o){if(o.querySelector(`.${n}`))return;const i=l();i.addEventListener("click",s),o.appendChild(i)}function a(){new MutationObserver(()=>{const i=c.selectors.composeToolbar.join(", ");if(!i)return;document.querySelectorAll(i).forEach(m=>u(m))}).observe(document.body,{childList:!0,subtree:!0})}chrome.runtime.onMessage.addListener(o=>{o.type==="INSERT_DRAFT"&&typeof o.text=="string"&&c.insertDraft(o.text)}),a()})();
